server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
spring:
  application:
    name: JudgeX-back
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/judgex
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1
codesandbox:
  defaultType: remote
file:
  prefix:
    user-dir: user
    judge-case-dir: judge-case
